### ISSUE TITLE
Not the same height and width of image

### ISSUE THREAD

**Issue by Sunshine352** [greentfrapp/boundary-attack#1]
In function 'orthogonal_perturbation', 
for i, channel in enumerate(diff):
	perturb[i] -= np.dot(perturb[i], channel) * channel
np.dot is matrix multiplication, if size of perturb[i] and channel is different, then came an error.

**Comment by greentfrapp** [comment]
Sorry for the really late reply, but this should be fixed in the latest commit. Do let me know if there are still issues!
