### ISSUE TITLE
the equation perturb[i] -= np.dot(perturb[i], channel) * channel? can i ask this meaning of this

### ISSUE THREAD

**Issue by lingmu12** [greentfrapp/boundary-attack#2]
the equation perturb[i] -= np.dot(perturb[i], channel) * channel. can i ask this meaning of this? Why does it get perturbations that are still on the sphere?

**Comment by htZhang25** [comment]
hello, I think the "np.dot(perturb[i], channel)" computes 
![image](https://user-images.githubusercontent.com/43310722/87268973-7f9db280-c4fe-11ea-8178-5c51568c44e6.png)
Here, we  see the vector a as perturb[i], see the vector b as channel, which represnts the direction of the diff(target, pre_sample).
So, we get cos(theta) *  a, this has projected perturbation onto sphere around target. Also, we can say it has projected perturbation onto the direction of vector b,  the direction of the diff(target, pre_sample).

**Comment by htZhang25** [comment]
Should it be np.vdot here? I hope somebody can help me.

**Comment by Lordworms** [comment]
hope someone can help. I got this problem 2

**Comment by greentfrapp** [comment]
Sorry for the really late reply! I'll be updating this repository with hopefully some extra explanations really soon!
