### ISSUE TITLE
question about "reshape()" in funcion "orthogonal_perturbation" .

### ISSUE THREAD

**Issue by htZhang25** [greentfrapp/boundary-attack#4]
When I read line32-33 in funcion "orthogonal_perturbation" in boundary-attack-resnet.py, I find
"
diff = diff.reshape(3, 224, 224) 
perturb = perturb.reshape(3, 224, 224),
"
why "reshape" is used, it will not simply change the order of channels.

In addition, I cannot undestand "perturb[i] -= np.dot(perturb[i], channel) * channel" in line35 in boundary-attack-resnet.py. I hope you can help me. Thank you very much.

**Comment by greentfrapp** [comment]
@htZhang25 really sorry for the super super late response but I'm finally getting around to fixing this repository. You are right that reshape should not be used in this case. Instead I should be using something like rollaxis or transpose.

I promise I'll be fixing this within these 2 days!
