### ISSUE TITLE
question about get_diff error

### ISSUE THREAD

**Issue by shifengzhao** [greentfrapp/boundary-attack#5]
I think you want to norm the perturbation according to channel. If so, in get_diff(), I think the reshape() should be changed by rollaxis(), because the reshape() cannot change channel last to channel first correctly.  If I am wrong, can you tell me the reason of get_diff()? Thanks.
![image](https://user-images.githubusercontent.com/39286101/101713807-5a27cb80-3ad3-11eb-8633-a16f5c9a2eee.png)

**Comment by greentfrapp** [comment]
@shifengzhao thanks for raising this, you are absolutely right!

I wrote this a pretty long time ago and made a few key mistakes in the implementation (as mentioned in other Issues as well!). I'll be fixing all of these within 48 hours and hopefully adding some bonus materials. Again, thanks for pointing this out!
