### ISSUE TITLE
Is this boundary attack implementation made by the paper's author?

### ISSUE THREAD

**Issue by machanic** [greentfrapp/boundary-attack#6]
Is this boundary attack implementation exactly the same with the procedure of the original official implementation, so that I can use it in my paper to report results?

**Comment by greentfrapp** [comment]
Hi @machanic, this implementation is not by the paper's author. I've tried to follow the implementation as best as I could. But you might also want to check out the implementation in Foolbox [here](https://github.com/bethgelab/foolbox/blob/042025ad9bee29aabf17b966d1c3e50fc6057ce3/foolbox/attacks/boundary_attack.py).

**Comment by greentfrapp** [comment]
Oh on that note, the Foolbox implementation is by the original authors.
