### ISSUE TITLE
How to support targeted attack?

### ISSUE THREAD

**Issue by machanic** [greentfrapp/boundary-attack#7]
I notice the `target_class = np.argmax(classifier.predict(target_sample))` defined in line 97 is never used. (https://github.com/greentfrapp/boundary-attack/blob/master/boundary-attack-resnet.py#L97)
How to modify this code to support targeted attack with predefined target label?

**Comment by machanic** [comment]
Do you mean `target_sample` and `target_class` in your code is actually the original clean image, rather than the target class label in targeted attack. Then how to support **untargeted attack** in this code?

**Comment by greentfrapp** [comment]
Yes the "target" is set via the original image. For an untargeted attack, you can refer to Section 2.1 of the original paper:
> In an untargeted scenario we simply sample from a maximum entropy distribution given the valid domain of the input.

They also give some details about how to sample this.
